- features/common/BUILD.bazel
- features/embedded/BUILD.bazel
- platforms/riscv32/devices.bzl
- platforms/riscv32/features/BUILD.bazel
- toolchains/lowrisc_rv32imcb/BUILD.bazel
- toolchains/lowrisc_rv32imcb/wrappers/BUILD
- toolchains/lowrisc_rv32imcb/wrappers/clang
Signed-off-by: Chris Frantz <cfrantz@google.com>
> [riscv32] Use clang instead of gcc

- toolchains/lowrisc_rv32imcb/repository.bzl
The SHA of the lowrisc toolchain archive was missing causing this to be incompatible in airgapped mode.
Signed-off-by: Timothy Trippel <ttrippel@google.com>
> Add missing sha256

- toolchains/cc65/wrappers/driver.sh
- toolchains/gcc_mxe_mingw64/wrappers/driver.sh
- toolchains/lowrisc_rv32imcb/wrappers/driver.sh
Some environments appear to remove even the standard binary dirs (like `/usr/bin`) from PATH.  Use bash built-ins to get the basename and dirname.
Signed-off-by: Chris Frantz <cfrantz@google.com>
> Eliminate basename/dirname in favor of bash builtins

- config/features.bzl
- platforms/riscv32/devices.bzl
- platforms/riscv32/features/BUILD.bazel
This adds support for and enables the use of the compiler hardening for unimp guards after jumps.
This patch does not enable the hardening when assembling assembly files, only for the C/C++ compilation/building steps. I also have an alternative patch set that does enable it for assembly files but it requires a new toolchain version and there is still an issue with the infrastructure for publicly updating the toolchains. To avoid being blocked on that any longer, I suggest this approach for now.
To minimize risk, I am making a separate PR for the shadow call stack hardening. I think it is better to enable the two hardenings separately.
> Add hardening jump guards

- config/compiler.bzl
- config/features.bzl
- features/common/BUILD.bazel
The `includes` feature was not expanding bazel-provided `includes`.  These `includes` are used to set build metadata for C compilation units.
> Correct `includes` for build stamping

- toolchains/cc65/BUILD.bazel
Signed-off-by: Chris Frantz <frantzcj@gmail.com>
> cc65 appears to need `--asminc` as well.

- BUILD.bazel
- config/registration.bzl
- deps.bzl
- platforms/riscv32/features/BUILD.bazel
- platforms/x86_32/BUILD.bazel
- platforms/x86_32/windows.bzl
- rules/pkg_win.bzl
- third_party/mxe/BUILD.mxe_src.bazel
- third_party/qemu/repos.bzl
- toolchains/cc65/repository.bzl
- toolchains/gcc_mxe_mingw32/BUILD.bazel
- toolchains/gcc_mxe_mingw32/repository.bzl
- toolchains/gcc_mxe_mingw32/repository.bzl.template
- toolchains/gcc_mxe_mingw32/wrappers/BUILD
- toolchains/gcc_mxe_mingw32/wrappers/ar
- toolchains/gcc_mxe_mingw32/wrappers/cpp
- toolchains/gcc_mxe_mingw32/wrappers/driver.sh
- toolchains/gcc_mxe_mingw32/wrappers/gcc
- toolchains/gcc_mxe_mingw32/wrappers/gcov
- toolchains/gcc_mxe_mingw32/wrappers/ld
- toolchains/gcc_mxe_mingw32/wrappers/nm
- toolchains/gcc_mxe_mingw32/wrappers/objcopy
- toolchains/gcc_mxe_mingw32/wrappers/objdump
- toolchains/gcc_mxe_mingw32/wrappers/strip
- toolchains/gcc_mxe_mingw64/repository.bzl
- util/BUILD.bazel
- util/pkg_win.py
1. Add build automation to build both Win32 and Win64 versions of the MXE gcc mingw32/64 toolchain.
2. Add a platform configuration for win32: `//platforms/x86_32:win32`.
3. Add a compiler configuration that uses the mingw32 compiler for `x86_32:win32`.
4. Fix the windows packing rules to behave appropriately with respect to the 32- or 64- bit toolchain.
> Add a `win32` compiler configuration

- deps.bzl
- platforms/x86_32/BUILD.bazel
- platforms/x86_64/BUILD.bazel
- platforms/x86_64/Windows-Qemu-Test-Setup.md
- third_party/qemu/BUILD.qemu.bazel
1. Add an execution config for `win32` that is distinct from `win64`.
2. Document how to create and use Windows disk images for testing.
Signed-off-by: Chris Frantz <cfrantz@google.com>
> Add a unique execution config for `win32`

- features/windows/BUILD.bazel
1. Don't place the timestamp in the PE-COFF header.
2. Disable LTO for windows `opt` builds.
Signed-off-by: Chris Frantz <cfrantz@google.com>
> Make builds hermetic for win32

- config/features.bzl
- platforms/riscv32/features/BUILD.bazel
- toolchains/lowrisc_rv32imcb/repository.bzl
- Updates the lowRISC toolchain version. In this update, the only difference should be a different implementation of the jump guards hardening. The new implementation no longer applies to assembly files.
- Updates jump guards hardening configuration. It removes the old constructs that were used to make the jump guards hardening only apply to source files. It also disables the jump guards hardening by default, so that we can conditionally enable it in OpenTitan's `.bazelrc` with `build --features=guards` or `--per_file_copt`, etc.
> Update toolchain jump guards hardening

- platforms/riscv32/features/BUILD.bazel
- toolchains/lowrisc_rv32imcb/BUILD.bazel
- toolchains/lowrisc_rv32imcb/repository.bzl
The toolchain release 20230427-1 updates Clang/LLVM to LLVM 16.0.2, plus support for:
- hardening patches.
- unratified bitmanip extensions.
- `.option arch` assembly directive.
> Update lowRISC toolchain version to 20230427-1

- platforms/riscv32/devices.bzl
- platforms/riscv32/features/BUILD.bazel
This enables the bit manipulation extensions Zba, Zbb, Zbc, and Zbs.
> Enable RISC-V ratified bitmanip extensions

- config/features.bzl
- features/common/BUILD.bazel
- features/embedded/BUILD.bazel
This PR adds some disabled features.
My goal is that I can gradually enable the features in OpenTitan by adding `--features=${new_feature}` to `.bazelrc`. Once I've worked through the new compilation errors, we can circle back and make these features enabled by default.
WDYT, @cfrantz?
> Add features for OpenTitan's missing compiler flags

- platforms/riscv32/devices.bzl
- platforms/riscv32/features/BUILD.bazel
Reverts lowRISC/crt#18
I'm reverting this because @luismarques told me this commit causes test failures in OpenTitan. It enables bitmanip unconditionally, but Englishbreakfast doesn't support bitmanip.
> Revert "Enable RISC-V ratified bitmanip extensions"

- config/features.bzl
- platforms/riscv32/devices.bzl
- platforms/riscv32/features/BUILD.bazel
This PR allows the riscv32 platform to be used with or without bitmanip. It uses a feature flag for this (see commit).
> Bitmanip feature

- features/common/BUILD.bazel
- features/embedded/BUILD.bazel
- tests/arm/notmain.c
- tests/riscv32/notmain.c
- tests/windows/sieve.c
- toolchains/BUILD.bazel
- toolchains/gcc_arm_none_eabi/repository.bzl
This should be a no-op with respect to OpenTitan's compiler flags.
The features added by PR #19 were disabled by default and manually enabled in OpenTitan's .bazelrc file (lowRISC/opentitan#18679). This commit enables those features by default.
(This is the final task in lowRISC/opentitan#12553.)
This PR also makes a few minor fixes:
* Fixes compiler errors in //tests. These were not errors prior to enabling Bazel features by default.
* Fixes a syntax error in //toolchains that prevented `bazel query` from functioning in this repo.
* Adds a sha256 value to the definition of `@gcc_arm_none_eabi_files`.
> Enable C/C++ warnings by default

- rules/transition.bzl
The `platform_target` rule is already created using `rv_rule` which sets the `cfg` attribute to make a platform transition on the outgoing edges of the rule. Therefore it is redundant to further make the `target` incoming edge of the rule also transition the platform. For some reason, `attr.label` will make `crt.attr.target` an array when `cfg` is set instead of just a single element. I could not find why in the bazel documentation.
> [transition] Remove useless configuration on rule attribute

- rules/local_archive.bzl
If one wants to use local_archive with a file path outside of the repository, a label is not ideal because we cannot use absolute file path (they will be interpreted as a target). This makes local_archive (and therefore http_archive_or_local with `local = /home/dev/bla/archive.tar.gz`) essentially unusable.
> [bazel] Fix local_archive to use a string instead of a label

- platforms/riscv32/features/BUILD.bazel
This makes the fastbuild and opt build configurations the same, since the `rust_binary` rule in `rules_rust` invokes the opt configuration on data deps.
> [riscv32] make fastbuild and opt the same

- rules/local_archive.bzl
1. If a local_archive path looks like a label, interpret it as such.
> Allow local_archive paths to be labels

- toolchains/lowrisc_rv32imcb/repository.bzl
This version of LLVM includes:
- Updated ePIC GPRel/PCRel rewrite rule to match the latest proposal.
- Backport LLD patches necessary for LTO and ePIC.
- Backport fix for incorrect debug info when linker relaxations are enabled.
> Update LLVM version with fixes

- features/common/BUILD.bazel
This flag catches easy to miss cases like this:
```c
for (uint8_t i = 5; i >= 0; --i) {
printf("hello!\n");
}
```
where a `uint8_t` will always be `>= 0`:
```console
[jw type-limits]$ clang -Wtype-limits main.c    
main.c:5:25: warning: result of comparison of unsigned expression >= 0 is always true [-Wtautological-unsigned-zero-compare]
for (uint8_t i = 5; i >= 0; --i) {
~ ^  ~
```
GCC includes this in `-Wextra`, but surprisingly Clang doesn't even include it in `-Wpedantic` at the moment and you have to go all the way up to `-Weverything`.
I haven't tested this because I can't get the CRT repo to build at the moment, but maybe it's simple enough.
> Add -Wtype-limits feature

- config/features.bzl
- features/common/BUILD.bazel
- rules/pkg_win.bzl
- third_party/bazel/repos.bzl
This PR contains three commits that:
1. updates the `platforms` dep from 0.0.5 to 0.0.10,
2. enables CC toolchain resolution across older and newer versions of Bazel which are used across lowRISC repos, and
3. enables distinguishing between C-only and C/C++ features, and fixes the `-Wstrict-prototypes` warning to only apply to C code, not C++ code (as specified by https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wstrict-prototypes)
> [features,pkg_win] fix feature and toolchain resolution bugs

- features/common/BUILD.bazel
Related to https://github.com/lowRISC/opentitan/pull/23358 and https://github.com/lowRISC/opentitan/issues/22928.
This commit enables the compiler warning to give some signal of potential bugs.
We still have many variables across the repo that are not marked with `OT_DISCARD` explicitly, so this change only enables warning, but not enforcing with error.
> Enable unused parameter / variable compiler warnings

- features/common/BUILD.bazel
When enabling LTO, Oz is required to have a smaller firmware size.
This PR adds the "minsize" feature, which will be enabled along with LTO on some ROM_EXT targets through bazel transition.
In our tests with ROM_EXT on the master branch,
* `Os + LTO` ~ +2,904 bytes
* `Oz      ` ~ -1,260 bytes
* `Oz + LTO` ~ -1,640 bytes
> [features] Add feature for Oz minsize opt level

- features/common/BUILD.bazel
- platforms/riscv32/features/BUILD.bazel
Only the last optimization level is effective.
To overwrite the level to Oz with the minsize feature flag, the feature needs to be listed after the compilation modes.
> [features] Fix minsize feature list order

- bazelisk.sh
- config/compiler.bzl
- config/registration.bzl
- toolchains/lowrisc_rv32imcb/BUILD.bazel
- toolchains/lowrisc_rv32imcb/repository.bzl
- toolchains/lowrisc_rv32imcb/wrappers/driver.sh
I could not find a way to read out the host architecture in lowrisc_rv32imcb_repos.
Using load("@local_config_platform//:constraints.bzl", "HOST_CONSTRAINTS")
at that stage leads to cycles in the workspace file.
Instead I now download both the ARM and X86 toolchains.
Next I register both and finally I let Bazel decide which one to use
as part of the automatic toolchain resolution.
> Add aarch64 support
